@php
    $isChinese = preg_match('/^zh(?:[-_]|$)/i', config('app.locale')) === 1;
    $dateFormat = $isChinese ? 'Y年n月j日' : 'F j, Y';
    $labels = $isChinese ? [
        'invoice' => '发票',
        'issuedDate' => '开具日期',
        'billedTo' => '账单接收方',
        'order' => '订单',
        'orderId' => '订单 ID',
        'type' => '类型',
        'serviceExpirationDate' => '服务到期日期',
        'deploymentInformation' => '部署信息',
        'server' => '服务器',
        'node' => '节点',
        'software' => '软件',
        'resources' => '资源',
        'memory' => '内存',
        'disk' => '磁盘',
        'charges' => '费用明细',
        'description' => '说明',
        'amount' => '金额',
        'discount' => '折扣',
        'deploymentFee' => '部署费（一次性）',
        'total' => '合计',
        'generatedBy' => '由 :name 生成',
    ] : [
        'invoice' => 'Invoice',
        'issuedDate' => 'Issued Date',
        'billedTo' => 'Billed To',
        'order' => 'Order',
        'orderId' => 'Order ID',
        'type' => 'Type',
        'serviceExpirationDate' => 'Service Expiration Date',
        'deploymentInformation' => 'Deployment Information',
        'server' => 'Server',
        'node' => 'Node',
        'software' => 'Software',
        'resources' => 'Resources',
        'memory' => 'Memory',
        'disk' => 'Disk',
        'charges' => 'Charges',
        'description' => 'Description',
        'amount' => 'Amount',
        'discount' => 'Discount',
        'deploymentFee' => 'Deployment Fee (one-time)',
        'total' => 'Total',
        'generatedBy' => 'Generated by :name',
    ];
    $orderTypes = $isChinese
        ? ['new' => '新购', 'renewal' => '续费', 'upgrade' => '升级']
        : ['new' => 'New Purchase', 'renewal' => 'Renewal', 'upgrade' => 'Upgrade'];
@endphp
<!DOCTYPE html>
<html lang="{{ $isChinese ? 'zh-CN' : 'en' }}">
<head>
    <meta charset="utf-8" />
    <style>
        body {
            font-family: 'Noto Sans CJK SC', 'Microsoft YaHei', 'PingFang SC', Arial, sans-serif;
            color: #2F3133;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        .header-table td {
            vertical-align: top;
            padding-bottom: 20px;
        }
        .brand {
            font-size: 18px;
            font-weight: bold;
            color: #2F3133;
        }
        .muted {
            color: #74787E;
        }
        .text-right {
            text-align: right;
        }
        .section-title {
            color: #2F3133;
            font-size: 13px;
            font-weight: bold;
            margin: 20px 0 8px 0;
            border-bottom: 1px solid #EDEFF2;
            padding-bottom: 4px;
        }
        .details-table td {
            padding: 3px 0;
        }
        .line-items {
            margin-top: 8px;
        }
        .line-items th {
            text-align: left;
            background-color: #F2F4F6;
            padding: 8px;
            font-size: 11px;
            color: #74787E;
            border-bottom: 1px solid #EDEFF2;
        }
        .line-items th.text-right {
            text-align: right;
        }
        .line-items td {
            padding: 8px;
            border-bottom: 1px solid #EDEFF2;
        }
        .total-row td {
            padding: 10px 8px;
            font-weight: bold;
            font-size: 14px;
            border-top: 2px solid #2F3133;
            border-bottom: none;
        }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #EDEFF2;
            color: #AEAEAE;
            font-size: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td width="50%">
                <div class="brand">{{ config('app.name') }}</div>
            </td>
            <td width="50%" class="text-right">
                <div><strong>{{ $labels['invoice'] }} {{ $snapshot['invoice_number'] }}</strong></div>
                <div class="muted">{{ $labels['issuedDate'] }}: {{ \Illuminate\Support\Carbon::parse($snapshot['issued_at'])->format($dateFormat) }}</div>
            </td>
        </tr>
    </table>

    <table>
        <tr>
            <td width="50%">
                <div class="section-title">{{ $labels['billedTo'] }}</div>
                <table class="details-table">
                    <tr><td>{{ $snapshot['billed_to']['username'] }}</td></tr>
                    <tr><td class="muted">{{ $snapshot['billed_to']['email'] }}</td></tr>
                </table>
            </td>
            <td width="50%">
                <div class="section-title">{{ $labels['order'] }}</div>
                <table class="details-table">
                    <tr><td class="muted">{{ $labels['orderId'] }}</td><td class="text-right">#{{ $snapshot['order_id'] }}</td></tr>
                    <tr>
                        <td class="muted">{{ $labels['type'] }}</td>
                        <td class="text-right">
                            {{ $orderTypes[$snapshot['order_type']] ?? $snapshot['order_type'] }}
                        </td>
                    </tr>
                    @if ($snapshot['expires_at'])
                        <tr>
                            <td class="muted">{{ $labels['serviceExpirationDate'] }}</td>
                            <td class="text-right">{{ \Illuminate\Support\Carbon::parse($snapshot['expires_at'])->format($dateFormat) }}</td>
                        </tr>
                    @endif
                </table>
            </td>
        </tr>
    </table>

    @if ($snapshot['server'] || $snapshot['node'] || $snapshot['egg'])
        <div class="section-title">{{ $labels['deploymentInformation'] }}</div>
        <table class="details-table">
            @if ($snapshot['server'])
                <tr><td class="muted" width="30%">{{ $labels['server'] }}</td><td>{{ $snapshot['server']['name'] }}</td></tr>
            @endif
            @if ($snapshot['node'])
                <tr><td class="muted">{{ $labels['node'] }}</td><td>{{ $snapshot['node']['name'] }} ({{ $snapshot['node']['fqdn'] }})</td></tr>
            @endif
            @if ($snapshot['egg'])
                <tr><td class="muted">{{ $labels['software'] }}</td><td>{{ $snapshot['egg']['name'] }}</td></tr>
            @endif
            @if ($snapshot['product'])
                <tr>
                    <td class="muted">{{ $labels['resources'] }}</td>
                    <td>
                        {{ $snapshot['product']['cpu_limit'] }}% CPU,
                        {{ number_format($snapshot['product']['memory_limit'] / 1024, 1) }} GiB {{ $labels['memory'] }},
                        {{ number_format($snapshot['product']['disk_limit'] / 1024, 1) }} GiB {{ $labels['disk'] }}
                    </td>
                </tr>
            @endif
        </table>
    @endif

    <div class="section-title">{{ $labels['charges'] }}</div>
    <table class="line-items">
        <thead>
            <tr>
                <th>{{ $labels['description'] }}</th>
                <th class="text-right">{{ $labels['amount'] }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($snapshot['line_items'] as $item)
                <tr>
                    <td>
                        @if (($snapshot['discount_code'] ?? null) && $item['description'] === "Discount ({$snapshot['discount_code']})")
                            {{ $labels['discount'] }}{{ $isChinese ? '（' : ' (' }}{{ $snapshot['discount_code'] }}{{ $isChinese ? '）' : ')' }}
                        @elseif ($item['description'] === 'Deployment Fee (one-time)')
                            {{ $labels['deploymentFee'] }}
                        @else
                            {{ $item['description'] }}
                        @endif
                    </td>
                    <td class="text-right">{{ $snapshot['currency']['symbol'] }}{{ number_format($item['amount'], 2) }}</td>
                </tr>
            @endforeach
            <tr class="total-row">
                <td>{{ $labels['total'] }}</td>
                <td class="text-right">{{ $snapshot['currency']['symbol'] }}{{ number_format($snapshot['total'], 2) }} {{ strtoupper($snapshot['currency']['code']) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        {{ str_replace(':name', config('app.name'), $labels['generatedBy']) }} &middot; {{ url('/') }}
    </div>
</body>
</html>
